// Generated by ts-to-zod
import { z } from 'zod';

export const loginRespondsSchema = z.string();

export const loginRespondsErrorSchema = z.string();

export const insertPitRespondSchema = z.number();

export const insertPitRespondErrorSchema = z.string();
