// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AveragesData, AveragesResponses, DeleteScoutData, DeleteScoutResponses, EditPitData, EditPitResponses, ForgiveScoutwarnData, ForgiveScoutwarnResponses, GetAllUsersData, GetAllUsersResponses, GetData, GetResponses, GetScoutwarnData, GetScoutwarnResponses, GetYearsData, GetYearsResponses, GraphData, GraphResponses, InsertData, InsertResponses, LoginData, LoginResponses, MvpInsertData, MvpInsertResponses, QueueData, QueuePlayoffData, QueuePlayoffResponses, QueueResponses, ScoutEditData, ScoutEditResponses, ScoutInsertData, ScoutInsertResponses, SearchData, SearchResponses, SendScoutwarnData, SendScoutwarnResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const editPit = <ThrowOnError extends boolean = false>(options: Options<EditPitData, ThrowOnError>) => (options.client ?? client).post<EditPitResponses, unknown, ThrowOnError>({
    url: '/api/pit/edit/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const get = <ThrowOnError extends boolean = false>(options: Options<GetData, ThrowOnError>) => (options.client ?? client).post<GetResponses, unknown, ThrowOnError>({
    url: '/api/pit/get',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const insert = <ThrowOnError extends boolean = false>(options: Options<InsertData, ThrowOnError>) => (options.client ?? client).post<InsertResponses, unknown, ThrowOnError>({
    url: '/api/pit/insert',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const forgiveScoutwarn = <ThrowOnError extends boolean = false>(options: Options<ForgiveScoutwarnData, ThrowOnError>) => (options.client ?? client).post<ForgiveScoutwarnResponses, unknown, ThrowOnError>({
    url: '/api/scoutwarn/forgive',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getScoutwarn = <ThrowOnError extends boolean = false>(options?: Options<GetScoutwarnData, ThrowOnError>) => (options?.client ?? client).get<GetScoutwarnResponses, unknown, ThrowOnError>({ url: '/api/scoutwarn/getall', ...options });

export const sendScoutwarn = <ThrowOnError extends boolean = false>(options: Options<SendScoutwarnData, ThrowOnError>) => (options.client ?? client).post<SendScoutwarnResponses, unknown, ThrowOnError>({
    url: '/api/scoutwarn/send',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const averages = <ThrowOnError extends boolean = false>(options: Options<AveragesData, ThrowOnError>) => (options.client ?? client).get<AveragesResponses, unknown, ThrowOnError>({ url: '/api/averages/{event}', ...options });

export const deleteScout = <ThrowOnError extends boolean = false>(options: Options<DeleteScoutData, ThrowOnError>) => (options.client ?? client).get<DeleteScoutResponses, unknown, ThrowOnError>({ url: '/api/delete/{id}', ...options });

export const graph = <ThrowOnError extends boolean = false>(options: Options<GraphData, ThrowOnError>) => (options.client ?? client).post<GraphResponses, unknown, ThrowOnError>({
    url: '/api/graph_sub',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const search = <ThrowOnError extends boolean = false>(options: Options<SearchData, ThrowOnError>) => (options.client ?? client).post<SearchResponses, unknown, ThrowOnError>({
    url: '/api/search',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>) => (options.client ?? client).post<LoginResponses, unknown, ThrowOnError>({
    url: '/api/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getYears = <ThrowOnError extends boolean = false>(options?: Options<GetYearsData, ThrowOnError>) => (options?.client ?? client).get<GetYearsResponses, unknown, ThrowOnError>({ url: '/api/snowgrave/get_years', ...options });

export const mvpInsert = <ThrowOnError extends boolean = false>(options: Options<MvpInsertData, ThrowOnError>) => (options.client ?? client).post<MvpInsertResponses, unknown, ThrowOnError>({
    url: '/api/mvp/insert',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const queue = <ThrowOnError extends boolean = false>(options: Options<QueueData, ThrowOnError>) => (options.client ?? client).post<QueueResponses, unknown, ThrowOnError>({
    url: '/api/snowgrave/queue_match',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const queuePlayoff = <ThrowOnError extends boolean = false>(options: Options<QueuePlayoffData, ThrowOnError>) => (options.client ?? client).post<QueuePlayoffResponses, unknown, ThrowOnError>({
    url: '/api/snowgrave/queue_match_playoff',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const scoutEdit = <ThrowOnError extends boolean = false>(options: Options<ScoutEditData, ThrowOnError>) => (options.client ?? client).post<ScoutEditResponses, unknown, ThrowOnError>({
    url: '/api/scout/edit',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const scoutInsert = <ThrowOnError extends boolean = false>(options: Options<ScoutInsertData, ThrowOnError>) => (options.client ?? client).post<ScoutInsertResponses, unknown, ThrowOnError>({
    url: '/api/scout/insert',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getAllUsers = <ThrowOnError extends boolean = false>(options?: Options<GetAllUsersData, ThrowOnError>) => (options?.client ?? client).get<GetAllUsersResponses, unknown, ThrowOnError>({ url: '/api/misc/get_all_users', ...options });
