// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://schima.json` | (string & {});
};

export type ApiResultForString = {
    status: 'Success';
    message: string;
} | {
    status: 'Error';
    message: string;
};

export type PitEditSpecific = {
    ExamplePit: Edit;
};

export type Edit = {
    width?: number | null;
    height?: number | null;
};

export type ApiResultForPitGetSend = {
    status: 'Success';
    message: PitGetSend;
} | {
    status: 'Error';
    message: string;
};

export type PitGetSend = {
    header: FullHeaderSend;
    pit: PitSpecific;
};

export type FullHeaderSend = {
    id: number;
    user: string;
    team: number;
    is_ab_team: boolean;
    event_code: string;
    created_at: string;
};

export type PitSpecific = {
    ExamplePit: Model;
};

export type Model = {
    id: number;
    width: number;
    height: number;
};

export type PitHeaderGetFront = {
    team: number;
    is_ab_team: boolean;
    event_code: string;
};

export type PitInsertForm = {
    pit_insert_id: number;
    pit: PitInsertsSpecific;
};

export type PitInsertsSpecific = {
    ExamplePit: Insert;
};

export type Insert = {
    width: number;
    height: number;
};

export type Forgive = {
    id: number;
};

export type ApiResultForArrayOfReturnWarningSend = {
    status: 'Success';
    message: Array<ReturnWarningSend>;
} | {
    status: 'Error';
    message: string;
};

export type ReturnWarningSend = {
    unsent_id: number;
    id: number;
    sender: string;
    receiver: string;
    message: string;
};

export type Message = {
    resv: string;
    message: string;
};

export type ApiResultForArrayOfGamesAvg = {
    status: 'Success';
    message: Array<GamesAvg>;
} | {
    status: 'Error';
    message: string;
};

export type GamesAvg = {
    team: number;
    total_score: number;
    game: GamesAvgSpecific;
};

export type GamesAvgSpecific = {
    ExampleGame: Avg;
};

export type Avg = {
    hehe_avg: number;
    beep_avg: number;
};

export type ApiResultForArrayOfArrayOfGamesGraph = {
    status: 'Success';
    message: Array<Array<GamesGraph>>;
} | {
    status: 'Error';
    message: string;
};

export type GamesGraph = {
    header: HeaderGraph;
    game: GamesGraphSpecific;
};

export type HeaderGraph = {
    time: string;
    total_score: number;
};

export type GamesGraphSpecific = {
    ExampleGame: Graph;
};

export type Graph = {
    hehe: number;
    beep: number;
};

export type GraphForm = {
    event?: string | null;
    teams: Array<number>;
};

export type ApiResultForArrayOfGamesFull = {
    status: 'Success';
    message: Array<GamesFull>;
} | {
    status: 'Error';
    message: string;
};

export type GamesFull = {
    header: HeaderFull;
    game: GamesFullSpecific;
};

export type HeaderFull = {
    id: number;
    user: string;
    team: number;
    is_ab_team: boolean;
    match_id: number;
    set: number;
    total_score: number;
    event_code: string;
    tournament_level: TournamentLevels;
    station: Stations;
    created_at: string;
    is_pending: boolean;
    is_marked: boolean;
    is_mvp: boolean;
    snowgrave_scout_id: number;
};

export type TournamentLevels = 'QualificationMatch' | 'Quarterfinal' | 'Semifinal' | 'Final';

export type Stations = 'Red1' | 'Red2' | 'Red3' | 'Blue1' | 'Blue2' | 'Blue3';

export type GamesFullSpecific = {
    ExampleGame: Model2;
};

export type Model2 = {
    id: number;
    hehe: number;
    beep: number;
    hoohoo: string;
};

export type SearchParamData = {
    user?: string | null;
    team?: number | null;
    is_ab_team?: boolean | null;
    match_id?: number | null;
    set?: number | null;
    total_score?: number | null;
    event_code?: string | null;
    tournament_level?: TournamentLevels | null;
    station?: Stations | null;
    is_mvp?: boolean | null;
};

export type EditPitData = {
    body: PitEditSpecific;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/pit/edit/{id}';
};

export type EditPitResponses = {
    200: ApiResultForString;
};

export type EditPitResponse = EditPitResponses[keyof EditPitResponses];

export type GetData = {
    body: PitHeaderGetFront;
    path?: never;
    query?: never;
    url: '/api/pit/get';
};

export type GetResponses = {
    200: ApiResultForPitGetSend;
};

export type GetResponse = GetResponses[keyof GetResponses];

export type InsertData = {
    body: PitInsertForm;
    path?: never;
    query?: never;
    url: '/api/pit/insert';
};

export type InsertResponses = {
    200: ApiResultForString;
};

export type InsertResponse = InsertResponses[keyof InsertResponses];

export type ForgiveScoutwarnData = {
    body: Forgive;
    path?: never;
    query?: never;
    url: '/api/scoutwarn/forgive';
};

export type ForgiveScoutwarnResponses = {
    200: ApiResultForString;
};

export type ForgiveScoutwarnResponse = ForgiveScoutwarnResponses[keyof ForgiveScoutwarnResponses];

export type GetScoutwarnData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/scoutwarn/getall';
};

export type GetScoutwarnResponses = {
    200: ApiResultForArrayOfReturnWarningSend;
};

export type GetScoutwarnResponse = GetScoutwarnResponses[keyof GetScoutwarnResponses];

export type SendScoutwarnData = {
    body: Message;
    path?: never;
    query?: never;
    url: '/api/scoutwarn/send';
};

export type SendScoutwarnResponses = {
    200: ApiResultForString;
};

export type SendScoutwarnResponse = SendScoutwarnResponses[keyof SendScoutwarnResponses];

export type AveragesData = {
    body?: never;
    path: {
        event: string;
    };
    query?: never;
    url: '/api/averages/{event}';
};

export type AveragesResponses = {
    200: ApiResultForArrayOfGamesAvg;
};

export type AveragesResponse = AveragesResponses[keyof AveragesResponses];

export type DeleteScoutData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/delete/{id}';
};

export type DeleteScoutResponses = {
    200: ApiResultForString;
};

export type DeleteScoutResponse = DeleteScoutResponses[keyof DeleteScoutResponses];

export type GraphData = {
    body: GraphForm;
    path?: never;
    query?: never;
    url: '/api/graph_sub';
};

export type GraphResponses = {
    200: ApiResultForArrayOfArrayOfGamesGraph;
};

export type GraphResponse = GraphResponses[keyof GraphResponses];

export type SearchData = {
    body: SearchParamData;
    path?: never;
    query?: never;
    url: '/api/search';
};

export type SearchResponses = {
    200: ApiResultForArrayOfGamesFull;
};

export type SearchResponse = SearchResponses[keyof SearchResponses];
