// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://schima.json` | (string & {});
};

export type ApiResultForString = {
    status: 'Success';
    message: string;
} | {
    status: 'Error';
    message: string;
};

export type PitEditSpecific = {
    ExamplePit: Edit;
};

export type Edit = {
    width?: number | null;
    height?: number | null;
};

export type ApiResultForPitGetSend = {
    status: 'Success';
    message: PitGetSend;
} | {
    status: 'Error';
    message: string;
};

export type PitGetSend = {
    header: FullHeaderSend;
    pit: PitSpecific;
};

export type FullHeaderSend = {
    id: number;
    user: string;
    team: number;
    is_ab_team: boolean;
    event_code: string;
    created_at: string;
};

export type PitSpecific = {
    ExamplePit: Model;
};

export type Model = {
    id: number;
    width: number;
    height: number;
};

export type PitHeaderGetFront = {
    team: number;
    is_ab_team: boolean;
    event_code: string;
};

export type PitInsertForm = {
    pit_insert_id: number;
    pit: PitInsertsSpecific;
};

export type PitInsertsSpecific = {
    ExamplePit: Insert;
};

export type Insert = {
    width: number;
    height: number;
};

export type Forgive = {
    id: number;
};

export type ApiResultForArrayOfPitScouterInstance = {
    status: 'Success';
    message: Array<PitScouterInstance>;
} | {
    status: 'Error';
    message: string;
};

export type PitScouterInstance = {
    id: number;
    event: string;
    team: number;
    is_ab_team: boolean;
    is_sum: boolean;
};

export type ApiResultForArrayOfReturnWarningSend = {
    status: 'Success';
    message: Array<ReturnWarningSend>;
} | {
    status: 'Error';
    message: string;
};

export type ReturnWarningSend = {
    unsent_id: number;
    id: number;
    sender: string;
    receiver: string;
    message: string;
};

export type Message = {
    resv: string;
    is_anon: boolean;
    message: string;
};

export type ApiResultForArrayOfGamesAvg = {
    status: 'Success';
    message: Array<GamesAvg>;
} | {
    status: 'Error';
    message: string;
};

export type GamesAvg = {
    team: number;
    total_score: number;
    game: GamesAvgSpecific;
};

export type GamesAvgSpecific = {
    ExampleGame: Avg;
};

export type Avg = {
    hehe_avg: number;
    beep_avg: number;
};

export type ApiResultForArrayOfGraphTeam = {
    status: 'Success';
    message: Array<GraphTeam>;
} | {
    status: 'Error';
    message: string;
};

export type GraphTeam = {
    data: Array<GamesGraph>;
    team: TeamData;
};

export type GamesGraph = {
    time: string;
    total_score: number;
    auto_score: number;
    teleop_score: number;
    defence: number;
};

export type TeamData = {
    is_ab_team: boolean;
    team: number;
};

export type GraphForm = {
    event?: string | null;
    teams: Array<TeamData>;
};

export type ApiResultForArrayOfGamesFull = {
    status: 'Success';
    message: Array<GamesFull>;
} | {
    status: 'Error';
    message: string;
};

export type GamesFull = {
    header: HeaderFull;
    game: GamesFullSpecific;
};

export type HeaderFull = {
    id: number;
    user: string;
    team: number;
    is_ab_team: boolean;
    match_id: number;
    set: number;
    total_score: number;
    auto_score: number;
    teleop_score: number;
    event_code: string;
    tournament_level: TournamentLevels;
    station: Stations;
    created_at: string;
    is_pending: boolean;
    is_marked: boolean;
    is_mvp: boolean;
    snowgrave_scout_id: number;
    defence: number;
};

export type TournamentLevels = 'QualificationMatch' | 'Quarterfinal' | 'Semifinal' | 'Final';

export type Stations = 'Red1' | 'Red2' | 'Red3' | 'Blue1' | 'Blue2' | 'Blue3';

export type GamesFullSpecific = {
    ExampleGame: Model2;
};

export type Model2 = {
    id: number;
    hehe: number;
    beep: number;
    hoohoo: string;
};

export type SearchParamData = {
    user?: string | null;
    team?: number | null;
    is_ab_team?: boolean | null;
    match_id?: number | null;
    set?: number | null;
    total_score?: number | null;
    event_code?: string | null;
    tournament_level?: TournamentLevels | null;
    station?: Stations | null;
    is_mvp?: boolean | null;
};

export type LoginRes = {
    Success: string;
} | {
    Error: string;
};

export type LoginForm = {
    username: string;
    password: string;
};

export type ApiResultForArrayOfGameForArrayOfScoutingTeamForScouterWithoutIdAndMvpIds = {
    status: 'Success';
    message: Array<GameForArrayOfScoutingTeamForScouterWithoutIdAndMvpIds>;
} | {
    status: 'Error';
    message: string;
};

export type GameForArrayOfScoutingTeamForScouterWithoutIdAndMvpIds = {
    id: number;
    event_code: string;
    match_id: number;
    set: number;
    tournament_level: TournamentLevels;
    teams: Array<ScoutingTeamForScouterWithoutId>;
    mvp: MvpIds;
};

export type ScoutingTeamForScouterWithoutId = {
    id: number;
    station: Stations;
    team: TeamData;
    scouters: Array<ScouterWithoutId>;
};

export type ScouterWithoutId = {
    id: number;
    station: Stations;
    done: boolean;
    is_redo: boolean;
};

export type MvpIds = {
    blue?: number | null;
    red?: number | null;
};

export type MvpInsert = {
    mvp_id: number;
    mvp_team: TeamData;
    comment: string;
    total_score: number;
    penalty_score: number;
};

export type QueueInput = {
    event: string;
};

export type EditSnow = {
    snowgrave_scout_id: number;
    defence?: number | null;
    game: GamesEditSpecific;
};

export type GamesEditSpecific = {
    ExampleGame: Edit2;
};

export type Edit2 = {
    hehe?: number | null;
    beep?: number | null;
    hoohoo?: string | null;
};

export type InsertSnow = {
    snowgrave_scout_id: number;
    game: GamesInsertsSpecific;
    defence: number;
};

export type GamesInsertsSpecific = {
    ExampleGame: Insert2;
};

export type Insert2 = {
    hehe: number;
    beep: number;
    hoohoo: string;
};

export type ApiResultForArrayOfString = {
    status: 'Success';
    message: Array<string>;
} | {
    status: 'Error';
    message: string;
};

export type ResetPasswordForm = {
    user: string;
    new_password: string;
};

export type ApiResultForArrayOfGame = {
    status: 'Success';
    message: Array<Game>;
} | {
    status: 'Error';
    message: string;
};

export type Game = {
    id: number;
    event_code: string;
    match_id: number;
    set: number;
    tournament_level: TournamentLevels;
    teams: Array<Team>;
    mvp_blue?: string | null;
    mvp_red?: string | null;
};

export type Team = {
    id: number;
    station: Stations;
    team: number;
    is_ab_team: boolean;
    scouters: Array<string>;
};

export type SetEvent = {
    event: string;
};

export type SubScoutForm = {
    og: string;
    replacement: string;
};

export type ApiResultForArrayOfSnowScouterDataLeaderBoard = {
    status: 'Success';
    message: Array<SnowScouterDataLeaderBoard>;
} | {
    status: 'Error';
    message: string;
};

export type SnowScouterDataLeaderBoard = {
    username: string;
    amount_of_warning: number;
};

export type ApiResultForArrayOfPitEvent = {
    status: 'Success';
    message: Array<PitEvent>;
} | {
    status: 'Error';
    message: string;
};

export type PitEvent = {
    id: number;
    team: number;
    is_ab_team: boolean;
    is_done: boolean;
    event_code: string;
};

export type AssignScoutFormButCool = {
    scouts: Array<string>;
    asignment: Array<PitAssigment>;
};

export type PitAssigment = {
    index: number;
    upcomingid: number;
};

export type ScouterInsertFront = {
    player_indexs: Array<string>;
    matches: Array<MatchData>;
};

export type MatchData = {
    upcoming_team_id: number;
    game_scouters: Array<GameTeamDataScouter>;
    mvp: GameTeamDataMvpFront;
};

export type GameTeamDataScouter = {
    index: number;
};

export type GameTeamDataMvpFront = {
    red: string;
    blue: string;
};

export type CreateUserForm = {
    username: string;
    password: string;
    is_admin: string;
};

export type ApiResultForArrayOfTeamWithAlliance = {
    status: 'Success';
    message: Array<TeamWithAlliance>;
} | {
    status: 'Error';
    message: string;
};

export type TeamWithAlliance = {
    is_blue: boolean;
    team: TeamData;
};

export type EditPitData = {
    body: PitEditSpecific;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/pit/edit/{id}';
};

export type EditPitResponses = {
    200: ApiResultForString;
};

export type EditPitResponse = EditPitResponses[keyof EditPitResponses];

export type GetData = {
    body: PitHeaderGetFront;
    path?: never;
    query?: never;
    url: '/api/pit/get';
};

export type GetResponses = {
    200: ApiResultForPitGetSend;
};

export type GetResponse = GetResponses[keyof GetResponses];

export type InsertData = {
    body: PitInsertForm;
    path?: never;
    query?: never;
    url: '/api/pit/insert';
};

export type InsertResponses = {
    200: ApiResultForString;
};

export type InsertResponse = InsertResponses[keyof InsertResponses];

export type ForgiveScoutwarnData = {
    body: Forgive;
    path?: never;
    query?: never;
    url: '/api/scoutwarn/forgive';
};

export type ForgiveScoutwarnResponses = {
    200: ApiResultForString;
};

export type ForgiveScoutwarnResponse = ForgiveScoutwarnResponses[keyof ForgiveScoutwarnResponses];

export type GetForScoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/pit/get_scouter';
};

export type GetForScoutResponses = {
    200: ApiResultForArrayOfPitScouterInstance;
};

export type GetForScoutResponse = GetForScoutResponses[keyof GetForScoutResponses];

export type GetScoutwarnData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/scoutwarn/getall';
};

export type GetScoutwarnResponses = {
    200: ApiResultForArrayOfReturnWarningSend;
};

export type GetScoutwarnResponse = GetScoutwarnResponses[keyof GetScoutwarnResponses];

export type SendScoutwarnData = {
    body: Message;
    path?: never;
    query?: never;
    url: '/api/scoutwarn/send';
};

export type SendScoutwarnResponses = {
    200: ApiResultForString;
};

export type SendScoutwarnResponse = SendScoutwarnResponses[keyof SendScoutwarnResponses];

export type AveragesData = {
    body?: never;
    path: {
        event: string;
    };
    query?: never;
    url: '/api/averages/{event}';
};

export type AveragesResponses = {
    200: ApiResultForArrayOfGamesAvg;
};

export type AveragesResponse = AveragesResponses[keyof AveragesResponses];

export type DeleteScoutData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/delete/{id}';
};

export type DeleteScoutResponses = {
    200: ApiResultForString;
};

export type DeleteScoutResponse = DeleteScoutResponses[keyof DeleteScoutResponses];

export type GraphData = {
    body: GraphForm;
    path?: never;
    query?: never;
    url: '/api/graph_sub';
};

export type GraphResponses = {
    200: ApiResultForArrayOfGraphTeam;
};

export type GraphResponse = GraphResponses[keyof GraphResponses];

export type SearchData = {
    body: SearchParamData;
    path?: never;
    query?: never;
    url: '/api/search';
};

export type SearchResponses = {
    200: ApiResultForArrayOfGamesFull;
};

export type SearchResponse = SearchResponses[keyof SearchResponses];

export type LoginData = {
    body: LoginForm;
    path?: never;
    query?: never;
    url: '/api/login';
};

export type LoginResponses = {
    200: LoginRes;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type GetYearsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/snowgrave/get_years';
};

export type GetYearsResponses = {
    200: ApiResultForArrayOfGameForArrayOfScoutingTeamForScouterWithoutIdAndMvpIds;
};

export type GetYearsResponse = GetYearsResponses[keyof GetYearsResponses];

export type MvpInsertData = {
    body: MvpInsert;
    path?: never;
    query?: never;
    url: '/api/mvp/insert';
};

export type MvpInsertResponses = {
    200: ApiResultForString;
};

export type MvpInsertResponse = MvpInsertResponses[keyof MvpInsertResponses];

export type QueueData = {
    body: QueueInput;
    path?: never;
    query?: never;
    url: '/api/snowgrave/queue_match';
};

export type QueueResponses = {
    200: ApiResultForString;
};

export type QueueResponse = QueueResponses[keyof QueueResponses];

export type QueuePlayoffData = {
    body: QueueInput;
    path?: never;
    query?: never;
    url: '/api/snowgrave/queue_match_playoff';
};

export type QueuePlayoffResponses = {
    200: ApiResultForString;
};

export type QueuePlayoffResponse = QueuePlayoffResponses[keyof QueuePlayoffResponses];

export type ScoutEditData = {
    body: EditSnow;
    path?: never;
    query?: never;
    url: '/api/scout/edit';
};

export type ScoutEditResponses = {
    200: ApiResultForString;
};

export type ScoutEditResponse = ScoutEditResponses[keyof ScoutEditResponses];

export type ScoutInsertData = {
    body: InsertSnow;
    path?: never;
    query?: never;
    url: '/api/scout/insert';
};

export type ScoutInsertResponses = {
    200: ApiResultForString;
};

export type ScoutInsertResponse = ScoutInsertResponses[keyof ScoutInsertResponses];

export type GetAllUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/misc/get_all_users';
};

export type GetAllUsersResponses = {
    200: ApiResultForArrayOfString;
};

export type GetAllUsersResponse = GetAllUsersResponses[keyof GetAllUsersResponses];

export type ResetPasswordData = {
    body: ResetPasswordForm;
    path?: never;
    query?: never;
    url: '/api/misc/reset_password';
};

export type ResetPasswordResponses = {
    200: ApiResultForString;
};

export type ResetPasswordResponse = ResetPasswordResponses[keyof ResetPasswordResponses];

export type GetAllSnowgraveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/snowgrave/all';
};

export type GetAllSnowgraveResponses = {
    200: ApiResultForArrayOfGame;
};

export type GetAllSnowgraveResponse = GetAllSnowgraveResponses[keyof GetAllSnowgraveResponses];

export type SetEventData = {
    body: SetEvent;
    path?: never;
    query?: never;
    url: '/api/set_event';
};

export type SetEventResponses = {
    200: ApiResultForString;
};

export type SetEventResponse = SetEventResponses[keyof SetEventResponses];

export type GetEventData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/get_event';
};

export type GetEventResponses = {
    200: ApiResultForString;
};

export type GetEventResponse = GetEventResponses[keyof GetEventResponses];

export type SubScoutData = {
    body: SubScoutForm;
    path?: never;
    query?: never;
    url: '/api/sub_scout';
};

export type SubScoutResponses = {
    200: ApiResultForString;
};

export type SubScoutResponse = SubScoutResponses[keyof SubScoutResponses];

export type GetLeaderboardData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/snowgrave/leaderboard';
};

export type GetLeaderboardResponses = {
    200: ApiResultForArrayOfSnowScouterDataLeaderBoard;
};

export type GetLeaderboardResponse = GetLeaderboardResponses[keyof GetLeaderboardResponses];

export type PitGetAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/pit/get_all';
};

export type PitGetAllResponses = {
    200: ApiResultForArrayOfPitEvent;
};

export type PitGetAllResponse = PitGetAllResponses[keyof PitGetAllResponses];

export type AssignPitData = {
    body: AssignScoutFormButCool;
    path?: never;
    query?: never;
    url: '/api/pit/assign';
};

export type AssignPitResponses = {
    200: ApiResultForString;
};

export type AssignPitResponse = AssignPitResponses[keyof AssignPitResponses];

export type InsertScoutData = {
    body: ScouterInsertFront;
    path?: never;
    query?: never;
    url: '/api/snowgrave/insert_scout';
};

export type InsertScoutResponses = {
    200: ApiResultForString;
};

export type InsertScoutResponse = InsertScoutResponses[keyof InsertScoutResponses];

export type CreateUserFrontData = {
    body: CreateUserForm;
    path?: never;
    query?: never;
    url: '/api/create_user';
};

export type CreateUserFrontResponses = {
    200: ApiResultForString;
};

export type CreateUserFrontResponse = CreateUserFrontResponses[keyof CreateUserFrontResponses];

export type GetTeamsFromGameData = {
    body?: never;
    path: {
        id_upcoming_game: number;
    };
    query?: never;
    url: '/api/pit/get_teams_from_game/{id_upcoming_game}';
};

export type GetTeamsFromGameResponses = {
    200: ApiResultForArrayOfTeamWithAlliance;
};

export type GetTeamsFromGameResponse = GetTeamsFromGameResponses[keyof GetTeamsFromGameResponses];
